sudo: false
language: perl
perl:
   - 'blead'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
   - '5.8'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - export OLD_CPANM_OPT=$PERL_CPANM_OPT
   - export PERL_CPANM_OPT='--mirror http://cpan.metacpan.org/ --mirror http://search.cpan.org/CPAN' $PERL_CPANM_OPT
   - cpanm --verbose RJBS/
   - cpanm --verbose RWSTAUNER/
   - cpanm --verbose JQUELIN/
   - cpanm --verbose RWSTAUNER/
   - cpanm --verbose STEVAN/
   - cpanm --verbose RJBS/
   - cpanm --verbose RJBS/
   - cpanm --verbose KEEDI/
   - cpanm --verbose BARBIE/
   - cpanm --verbose --installdeps RJBS/
   - cpanm --verbose --installdeps RWSTAUNER/
   - cpanm --verbose --installdeps JQUELIN/
   - cpanm --verbose --installdeps RWSTAUNER/
   - cpanm --verbose --installdeps STEVAN/
   - cpanm --verbose --installdeps RJBS/
   - cpanm --verbose --installdeps RJBS/
   - cpanm --verbose --installdeps KEEDI/
   - cpanm --verbose --installdeps BARBIE/
   - export PERL_CPANM_OPT=$OLD_CPANM_OPT
script:
   - dzil smoke --release --author
